name: private-isu
services:
  nginx:
    image: nginx:1.28
    depends_on:
      - app
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
    ports:
      - "80:80"
    networks:
      - my_network

  app:
    build:
      # Go実装の場合は golang/ PHP実装の場合は php/ Python実装の場合は python/ に変更
      context: python/
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - memcached
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
      # AWS Application Signals configuration
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_AWS_APPLICATION_SIGNALS_ENABLED: "true"
      OTEL_PYTHON_DISTRO: aws_distro
      OTEL_PYTHON_CONFIGURATOR: aws_configurator
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_TRACES_SAMPLER: xray
      OTEL_TRACES_SAMPLER_ARG: "endpoint=http://localhost:2000"
      OTEL_AWS_APPLICATION_SIGNALS_EXPORTER_ENDPOINT: http://localhost:4316/v1/metrics
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://localhost:4316/v1/traces
      OTEL_RESOURCE_ATTRIBUTES: "service.name=private-isucon,deployment.environment=isucon"
      AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
      AWS_XRAY_LOG_LEVEL: info
      AWS_XRAY_TRACING_NAME: private-isu
      AWS_XRAY_TRACE_SQL_QUERIES: true
    networks:
      - my_network
    volumes:
      - ./public:/home/public
    init: true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g

  mysql:
    image: mysql:8.4
    environment:
      #- "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g

  memcached:
    image: memcached:1.6
    networks:
      - my_network

volumes:
  mysql:

networks:
  my_network:
