name: private-isu
services:
  nginx:
    image: nginx:1.28
    depends_on:
      - app
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
    ports:
      - "80:80"
    networks:
      - my_network

  app:
    build:
      # Go実装の場合は golang/ PHP実装の場合は php/ Python実装の場合は python/ に変更
      context: python/
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - memcached
      - xray
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
      AWS_XRAY_DAEMON_ADDRESS: xray:2000
      AWS_XRAY_TRACING_NAME: private-isu
      _AWS_XRAY_DAEMON_PORT: 2000
      _AWS_XRAY_DAEMON_ADDRESS: xray
    networks:
      - my_network
    volumes:
      - ./public:/home/public
    init: true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g

  mysql:
    image: mysql:8.4
    environment:
      #- "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g

  memcached:
    image: memcached:1.6
    networks:
      - my_network

  xray:
    image: amazon/aws-xray-daemon:latest
    ports:
      - "2000:2000/udp"
      - "2000:2000/tcp"
    environment:
      AWS_REGION: ap-northeast-1
    networks:
      - my_network
    command: ["--bind=0.0.0.0:2000", "--log-level=info"]

volumes:
  mysql:

networks:
  my_network:
